#!/usr/bin/env python3
import requests
from bs4 import BeautifulSoup

#Establishing proxies to route requests over a TOR circuit
proxies= {
        'http': 'socks5h://127.0.0.1:9050',
        'https': 'socks5h://127.0.0.1:9050',
}

# Get the URL file name from the user
urls_filename = input("Enter the file name containing the URLs: ") 

# Read the URLs from the file
with open(urls_filename, "r") as file:
    urls = file.readlines()

#Sending the web request and storing the page sourcecode
html = requests.get(urls, proxies=proxies, verify=False)

#Parsing page sourcecode with beautifulsoup and retrieving the title
soup = BeautifulSoup(html.text, "html.parser")
title = ("Page title: ", soup.title.string)

#Checking for response from domain and printing result to standard output
if html.status_code == 200:
        print(title)
        print("is up and responding.")
else:
        print("Domain not reachable. Please try again later.")
